import Link from "next/link";
import { notFound } from "next/navigation";
import { api, apiText, ApiError } from "@/lib/api";
import type { LabOrder } from "@/lib/types";

/**
 * The tube labels for one order, laid out to print.
 *
 * The barcodes are fetched on the server and inlined as markup rather than referenced with `<img>`,
 * because the bearer token lives in an httpOnly cookie: a browser-issued request for the label would
 * arrive unauthenticated. Inlining also means the vectors go straight to the printer with no
 * intermediate raster step, which is what keeps the bars the right width relative to each other.
 *
 * Deliberately plain. This page exists to come out of a label printer, so it carries no navigation
 * chrome, and `print:hidden` removes the one control that would otherwise waste a label.
 */
export default async function SpecimenLabelsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  let order: LabOrder;
  try {
    order = await api<LabOrder>(`/lab/orders/${id}`);
  } catch (error) {
    if (error instanceof ApiError && error.status === 404) notFound();
    throw error;
  }

  // One label per specimen. An order collected into two tubes needs two, each with its own
  // accession number - the number is per specimen, not per order.
  const labels = await Promise.all(
    order.specimens.map(async (specimen) => ({
      specimen,
      svg: await apiText(`/lab/specimens/${encodeURIComponent(specimen.accessionNo)}/label`,
        "image/svg+xml"),
    })),
  );

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3 print:hidden">
        <div>
          <h1 className="text-xl font-semibold tracking-tight">Specimen labels</h1>
          <p className="numeric text-sm text-ink-muted">
            {order.patientMrn} · {order.items.map((item) => item.testName).join(", ")}
          </p>
        </div>
        <Link
          href={`/laboratory/${order.id}`}
          className="rounded border border-line px-3 py-1.5 text-sm hover:bg-surface"
        >
          Back to the report
        </Link>
      </div>

      {labels.length === 0 ? (
        <p className="rounded border border-line bg-surface p-4 text-sm text-ink-muted print:hidden">
          Nothing to print yet — no specimen has been collected against this order.
        </p>
      ) : (
        <div className="flex flex-wrap gap-4">
          {labels.map(({ specimen, svg }) => (
            <figure
              key={specimen.id}
              className="rounded border border-line bg-white p-2 print:border-0"
            >
              {/*
                The SVG comes from our own gateway, generated by SpecimenLabelRenderer from a
                sequence-issued accession number, and every interpolated value in it is XML-escaped
                at the source. It is not user-supplied markup.
              */}
              <div dangerouslySetInnerHTML={{ __html: svg }} />
              <figcaption className="mt-1 text-center text-xs text-ink-muted print:hidden">
                {specimen.specimenType.toLowerCase().replace(/_/g, " ")} · {specimen.status.toLowerCase()}
              </figcaption>
            </figure>
          ))}
        </div>
      )}
    </div>
  );
}
